# Generated by Django 2.2.1 on 2019-05-01 09:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('outline', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stype', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('fov', models.IntegerField(default=10)),
                ('rng', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='SensorPlacements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_sensors.Sensors')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_sensors.Locations')),
            ],
            options={
                'unique_together': {('site', 'sensor')},
            },
        ),
    ]
